@startuml
Title: Database::initialize()

main -> main: register signal handlers
main -> main: create new Database
main -> Database: initialize()
Database -> main:
main -> Database: verify()
alt verify() returns false
	Database -> main: false
	main -> System: terminate program with error

else verify() returns true
	Database -> main: true
	Database -> DataController: open()
	DataController -> PrimaryDatastore: initialize()
	PrimaryDatastore -> DataController:
	DataController -> Database:

	participant "Network Subsystem" as Network

	Database -> Network: initialize()
	Network -> Database:
	loop until termination is requested
		Database -> Network: listen()
		Network -> Database: ClientConnection
		group new thread
			Database -> ClientConnection: threadEntry()
		end
	end
	Database -> Network: close()
	Network -> Database:
	Database -> Database: stop()
	Database -> System: terminate program with success
end
@enduml

@startuml
Title: Database: Handle System Signals
'TODO: process more signals?

System -> Database: send Signal
Database -> Database: process Signal
alt Signal is Termination Signal
	Database -> Database: kick Clients
	Database -> Network: close() 
	Network -> Database:
	Database -> DataController: close()
	DataController -> Database:
	Database -> System: end process
else Signal is not Termination Signal
	Database -> Database: ignore signal
end
@enduml