@startuml
Title: Datastore::initialize

Datastore -> Datastore: createIndex()
@enduml

@startuml
Title: Datastore::createIndex

loop for each Record on Disk
	Datastore -> Disk: readRecordFromSource()
	Disk -> Datastore: return Record
	Datastore -> Index: addRecord()
	Index -> Datastore:
end
@enduml