Journal
=======

// TODO: initialization

@startuml
Title: Journal: Preprocess

Journal -> Disk: read Journal
Disk -> Journal: ok
'TODO: This section needs some work as the concept of a TOC is no longer relevant
loop for each Journal Entry in Journal
	alt Journal Entry deletes Record
		Journal -> Datastore: mark Record as deleted in Index
		Datastore -> Journal: ok
	end
	alt Journal Entry sets Record
		Journal -> Datastore: mark Record as set with Journal Entry's Id in TOC
		Datastore -> Journal: ok
	end
end
@enduml

@startuml
Title: Journal: Apply To Datastore
participant Disk

Journal -> Disk: get Journal
Disk -> Journal: Journal
loop for each Journal Entry in Journal
	Journal -> Datastore: compare Record from Journal Entry to TOC
	alt if Record is not deleted and Journal Entry Id is not older than set Journal Entry
		Datastore -> Journal: Record needs to be processed
		Journal -> Datastore: Process Journal Entry Event with Datastore
	else Record is deleted or Journal Entry Id is older than set Journal Entry
		Datastore -> Journal: Record does not need to be processed
		Journal -> Journal: ignore Record
	end
end
@enduml